image:
  repository: gitlab/gitlab-ce
  pullPolicy: IfNotPresent
  tag: 16.7.0-ce.0
securityContext:
  containers:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              initialDelaySeconds: 30
              type: tcp
            readiness:
              initialDelaySeconds: 30
              type: tcp
            startup:
              initialDelaySeconds: 30
              type: tcp
          env:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'https://gitlab.vgavin.keenetic.link'
              nginx['listen_port'] = 80
              nginx['listen_https'] = false
              gitlab_rails['initial_root_password'] = "dolpher573NO"
              nginx['proxy_set_headers'] = {
                "X-Forwarded-Proto" => "http",
                "X-Forwarded-Port" => "80",
                "X-Forwarded-Host" => "gitlab.vgavin.keenetic.link"
              }
    type: StatefulSet
    replicas: 1
    strategy: RollingUpdate
portal:
  open:
    enabled: false
